#!/bin/bash -eu

lerna run --parallel --bail --ignore "jest-fixture-injection-example-cra" test
lerna run --concurrency 1 --stream --bail --scope "jest-fixture-injection-example-cra" test -- --coverage
