#!/bin/bash -eu

lerna run --parallel --bail --ignore "jest-fixture-injection-example-cra" test
CI="1" lerna run --concurrency 1 --stream --bail --scope "jest-fixture-injection-example-cra" \
  test -- --all
